//go:build !ignore_autogenerated

package v1

import "k8s.io/apimachinery/pkg/runtime"

func copyStringMap(in map[string]string) map[string]string {
	if in == nil {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (in *Disk) DeepCopyInto(out *Disk) { *out = *in; out.Spec.Labels = copyStringMap(in.Spec.Labels) }
func (in *Disk) DeepCopy() *Disk {
	if in == nil {
		return nil
	}
	out := new(Disk)
	in.DeepCopyInto(out)
	return out
}
func (in *Disk) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DiskList) DeepCopyInto(out *DiskList) {
	*out = *in
	if in.Items != nil {
		out.Items = make([]Disk, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *DiskList) DeepCopy() *DiskList {
	if in == nil {
		return nil
	}
	out := new(DiskList)
	in.DeepCopyInto(out)
	return out
}
func (in *DiskList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *DiskClaim) DeepCopyInto(out *DiskClaim) { *out = *in }
func (in *DiskClaim) DeepCopy() *DiskClaim {
	if in == nil {
		return nil
	}
	out := new(DiskClaim)
	in.DeepCopyInto(out)
	return out
}
func (in *DiskClaim) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DiskClaimList) DeepCopyInto(out *DiskClaimList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]DiskClaim(nil), in.Items...)
	}
}
func (in *DiskClaimList) DeepCopy() *DiskClaimList {
	if in == nil {
		return nil
	}
	out := new(DiskClaimList)
	in.DeepCopyInto(out)
	return out
}
func (in *DiskClaimList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *UnassignedDisk) DeepCopyInto(out *UnassignedDisk) { *out = *in }
func (in *UnassignedDisk) DeepCopy() *UnassignedDisk {
	if in == nil {
		return nil
	}
	out := new(UnassignedDisk)
	in.DeepCopyInto(out)
	return out
}
func (in *UnassignedDisk) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *UnassignedDiskList) DeepCopyInto(out *UnassignedDiskList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]UnassignedDisk(nil), in.Items...)
	}
}
func (in *UnassignedDiskList) DeepCopy() *UnassignedDiskList {
	if in == nil {
		return nil
	}
	out := new(UnassignedDiskList)
	in.DeepCopyInto(out)
	return out
}
func (in *UnassignedDiskList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *StoragePool) DeepCopyInto(out *StoragePool) {
	*out = *in
	out.Spec.DiskSelector = copyStringMap(in.Spec.DiskSelector)
	if in.Spec.ParityDisks != nil {
		out.Spec.ParityDisks = append([]string(nil), in.Spec.ParityDisks...)
	}
}
func (in *StoragePool) DeepCopy() *StoragePool {
	if in == nil {
		return nil
	}
	out := new(StoragePool)
	in.DeepCopyInto(out)
	return out
}
func (in *StoragePool) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *StoragePoolList) DeepCopyInto(out *StoragePoolList) {
	*out = *in
	if in.Items != nil {
		out.Items = make([]StoragePool, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *StoragePoolList) DeepCopy() *StoragePoolList {
	if in == nil {
		return nil
	}
	out := new(StoragePoolList)
	in.DeepCopyInto(out)
	return out
}
func (in *StoragePoolList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Filesystem) DeepCopyInto(out *Filesystem) { *out = *in }
func (in *Filesystem) DeepCopy() *Filesystem {
	if in == nil {
		return nil
	}
	out := new(Filesystem)
	in.DeepCopyInto(out)
	return out
}
func (in *Filesystem) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *FilesystemList) DeepCopyInto(out *FilesystemList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]Filesystem(nil), in.Items...)
	}
}
func (in *FilesystemList) DeepCopy() *FilesystemList {
	if in == nil {
		return nil
	}
	out := new(FilesystemList)
	in.DeepCopyInto(out)
	return out
}
func (in *FilesystemList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Share) DeepCopyInto(out *Share) { *out = *in }
func (in *Share) DeepCopy() *Share {
	if in == nil {
		return nil
	}
	out := new(Share)
	in.DeepCopyInto(out)
	return out
}
func (in *Share) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ShareList) DeepCopyInto(out *ShareList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]Share(nil), in.Items...)
	}
}
func (in *ShareList) DeepCopy() *ShareList {
	if in == nil {
		return nil
	}
	out := new(ShareList)
	in.DeepCopyInto(out)
	return out
}
func (in *ShareList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Volume) DeepCopyInto(out *Volume) { *out = *in }
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}
func (in *Volume) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *VolumeList) DeepCopyInto(out *VolumeList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]Volume(nil), in.Items...)
	}
}
func (in *VolumeList) DeepCopy() *VolumeList {
	if in == nil {
		return nil
	}
	out := new(VolumeList)
	in.DeepCopyInto(out)
	return out
}
func (in *VolumeList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *TierPolicy) DeepCopyInto(out *TierPolicy) { *out = *in }
func (in *TierPolicy) DeepCopy() *TierPolicy {
	if in == nil {
		return nil
	}
	out := new(TierPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *TierPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *TierPolicyList) DeepCopyInto(out *TierPolicyList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]TierPolicy(nil), in.Items...)
	}
}
func (in *TierPolicyList) DeepCopy() *TierPolicyList {
	if in == nil {
		return nil
	}
	out := new(TierPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *TierPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *DiskLock) DeepCopyInto(out *DiskLock) { *out = *in }
func (in *DiskLock) DeepCopy() *DiskLock {
	if in == nil {
		return nil
	}
	out := new(DiskLock)
	in.DeepCopyInto(out)
	return out
}
func (in *DiskLock) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DiskLockList) DeepCopyInto(out *DiskLockList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]DiskLock(nil), in.Items...)
	}
}
func (in *DiskLockList) DeepCopy() *DiskLockList {
	if in == nil {
		return nil
	}
	out := new(DiskLockList)
	in.DeepCopyInto(out)
	return out
}
func (in *DiskLockList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *PoolHealth) DeepCopyInto(out *PoolHealth) { *out = *in }
func (in *PoolHealth) DeepCopy() *PoolHealth {
	if in == nil {
		return nil
	}
	out := new(PoolHealth)
	in.DeepCopyInto(out)
	return out
}
func (in *PoolHealth) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *PoolHealthList) DeepCopyInto(out *PoolHealthList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]PoolHealth(nil), in.Items...)
	}
}
func (in *PoolHealthList) DeepCopy() *PoolHealthList {
	if in == nil {
		return nil
	}
	out := new(PoolHealthList)
	in.DeepCopyInto(out)
	return out
}
func (in *PoolHealthList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *FilesystemIntegrity) DeepCopyInto(out *FilesystemIntegrity) { *out = *in }
func (in *FilesystemIntegrity) DeepCopy() *FilesystemIntegrity {
	if in == nil {
		return nil
	}
	out := new(FilesystemIntegrity)
	in.DeepCopyInto(out)
	return out
}
func (in *FilesystemIntegrity) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *FilesystemIntegrityList) DeepCopyInto(out *FilesystemIntegrityList) {
	*out = *in
	if in.Items != nil {
		out.Items = append([]FilesystemIntegrity(nil), in.Items...)
	}
}
func (in *FilesystemIntegrityList) DeepCopy() *FilesystemIntegrityList {
	if in == nil {
		return nil
	}
	out := new(FilesystemIntegrityList)
	in.DeepCopyInto(out)
	return out
}
func (in *FilesystemIntegrityList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
